### ISSUE TITLE
How to change mutation probability table?

### ISSUE THREAD

**Issue by LIKUOKUO** [jamesware/denovolyzeR#15]
This is not a issue, but I do not know how to change mutation probability table. when I use internal  probability table like the code blow, it also return same error. Hope to get your help,thanks
denovolyzeByClass(genes=data$hgncID,
                           classes=data$ExonicFunc.refGene,
                           includeClasses = c("syn", "mis","misD", "lof","protD"),geneId = 
                          "hgncID",nsamples=5165,**probTable = viewProbabilityTable()**)

**Error**
Error in parseInput(genes, classes, nsamples, groupBy, includeGenes, includeClasses,  : 
  The following are not recognised variant classes: synThe following are not recognised variant classes: misThe following are not recognised variant classes: misDThe following are not recognised variant classes: spliceThe following are not recognised variant classes: nonThe following are not recognised variant classes: frameshiftThe following are not recognised variant classes: stoploss
In addition: Warning message:

**Comment by jamesware** [comment]
It looks like your probability table is not in the correct format.

`viewProbabilityTable()` shows the table in "wide" format for human readability.
`viewProbabilityTable(format="long")` shows the table in long format, which is how the data is stored internally
viewProbabilityTable is a convenience function - you can see the internal probability tables with `head(denovolyzeR:::pDNM)`

I don't have your input data to check the error, but if I use the internal data then the following works:
```
myProbTable <- viewProbabilityTable(format="long")

denovolyzeByClass(genes=denovolyzeR::autismDeNovos$gene,
                  classes=denovolyzeR::autismDeNovos$class,
                  includeClasses = c("syn", "mis","misD", "lof","protD"),
                  nsamples=1000,
                  probTable=myProbTable)
```

I hope that solves your problem.
