### ISSUE TITLE
Error about the class of "misD"

### ISSUE THREAD

**Issue by JieyiChen0821** [jamesware/denovolyzeR#16]
Dear author!
  I prepared a list of gene and class like the demo:
class,gene
syn,AFF2
misD,AFF2
mis,AGAP3
mis,AGAP3
frameshift,ANKRD34A
frameshift,ANKRD34A
frameshift,ASXL1
misD,BTBD9
frameshift,COG5
mis,CTPS2
misD,FLNA
mis,IGSF1
frameshift,INO80E
non,MGAT3
non,MGAT3
syn,NHSL2
splice,TDG
syn,TFDP3
mis,TFDP3
mis,THEMIS2
mis,THEMIS2

I ran the code and met the error:
``` denovolyze(genes = data$gene,classes = data$class,nsamples = 57) ```
_Error in parseInput(genes, classes, nsamples, groupBy, includeGenes, includeClasses,  : 
  The following are not recognised variant classes: misD_

Then I tired to change the  parameters like misD, includeClasses:
```denovolyze(genes = data$gene,classes = data$class,nsamples = 57 ,groupBy="class",geneId = "geneName",includeGenes = "all",  misD = "misD")```
```denovolyze(genes = data$gene,classes = data$class,nsamples = 57 ,groupBy="class",geneId = "geneName",includeGenes = "all",  misD = "misD",includeClasses = c("syn", "mis", "misD", "non", "splice", "frameshift", "lof", "all")) ```
However, they didn't worl at all and the same error happened...

I failed to find the solution or detailed information of the usage about "misD". Can you help me to deal with the problem? Thanks a lot!

**Comment by JieyiChen0821** [comment]
I also want to use some addional labels like "Damaging" "In-frame indels" used in this article: https://www.ncbi.nlm.nih.gov/pubmed/31292255
How can I annoted such information to the default model or dataset provided by the package of denovolyzeR ?

**Comment by jamesware** [comment]
Hi,
the probability tables within denovolyzeR are based on major variant classes output by ensembl VEP (sys, mis, non, splice & frameshift; and aggregated labels lof & prot (= protein-altering)).  The built-in probability table does not include deleterious missense stratified by a prediction algorithm. 

To use this functionality you need to define a subset of "damaging missense" that suits your purpose, and provide a probability table that has the appropriate probabilities, using the `probTable` argument.  You would base this on the internal data structure `viewProbabilityTables()`, but adding a new set of probabilities labelled "misD".  I recall that you need to pass this to the `denovolyze()` function in long format (as in `viewProbabilityTables(format="long")`).

We published probability tables that included a damaging missense subset in https://science.sciencemag.org/content/350/6265/1262/ (see supplementary databases S4 & S5).  These included a coverage correction for the specific sequencing platforms used in this study - you could check whether one of them provides a good fit for your model, but it may be preferable to compute your own.
Have the authors of the paper you cite (31292255) made their tables publicly available?

I _think_ you should have no problem adding additional variant classes as long as they are in your user-provided probability table and you use the same label in the both the `includeClasses` argument and the `class` column of the new probability table.

If you generate some probability tables that include additional subclassifications I would be happy to add them to https://github.com/jamesware/denovolyzeR/tree/master/alternativeProbabilityTables
to help others.

Best wishes,
James
