### ISSUE TITLE
used for pig

### ISSUE THREAD

**Issue by yinhongwei4079** [jamesware/denovolyzeR#17]
i want to use it to predict variants for pigs and didn't kown if it can used for pigs. If not, could you give me some advice?

**Comment by jamesware** [comment]
I think the statistics would be valid, but the built-in probability tables are for human genes. Please could you describe your planned analysis and I can make a few suggestions.

Sent from a mobile device

On Aug 2, 2021, at 00:57, yinhongwei4079 ***@***.***> wrote:

﻿
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



i want to use it to predict variants for pigs and didn't kown if it can used for pigs. If not, could you give me some advice?

**Comment by yinhongwei4079** [comment]
Hi @jamesware 
Thanks so much for your reply! Actually we aim to evaluate the mutational constraint in pig, so we would like to calculate the pLI score for a given gene. The prerequisite is to calculate the number of expected mutations for a given gene. We found your software package being able to do that, but only for human, so we are wondering if possible to extend your package in pig? Specifically, how we can build the probability tables for pig genes. Or even better you know how to calculate pLI score for a given porcine gene? We are open to collaborate depending on your interests. Thanks again!
 
Best,
Hongwei

**Comment by jamesware** [comment]
Let's move this conversation from GitHub issue tracker to email - can you send me your email address?  I am j.ware  (imperial.ac.uk)
